# Generated by Django 6.0.1 on 2026-02-04 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_teamtype_order'),
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.teamtype'),
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
