# Generated by Django 6.0.1 on 2026-01-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_myclub_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myclub',
            options={'verbose_name': 'MyClub', 'verbose_name_plural': 'MyClub'},
        ),
    ]
