# Generated by Django 6.0.1 on 2026-02-04 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_myclub_options'),
        ('teams', '0011_alter_coach_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclub',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='teams.team'),
        ),
    ]
