# Generated by Django 6.0.1 on 2026-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_myclub_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclub',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myclub',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myclub',
            name='stadium',
            field=models.TextField(blank=True, null=True),
        ),
    ]
