# Generated by Django 6.0.1 on 2026-02-09 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_myclub_achievements_myclub_history_myclub_stadium'),
        ('teams', '0015_alter_coach_position_alter_management_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclub',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.team'),
        ),
    ]
