# Generated by Django 6.0.1 on 2026-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clubsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsocial',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
