# Generated by Django 6.0.1 on 2026-02-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='working_hours',
        ),
    ]
