# Generated by Django 6.0.1 on 2026-04-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clubsocial_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
