# Generated by Django 6.0.1 on 2026-02-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='league/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.league')),
                ('team_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.teamtype')),
            ],
        ),
    ]
