# Generated by Django 6.0.1 on 2026-01-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
