# Generated by Django 6.0.1 on 2026-02-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_season_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='season',
            name='team_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.teamtype'),
        ),
    ]
