# Generated by Django 6.0.1 on 2026-02-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_teamtype_alter_season_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
