# Generated by Django 6.0.1 on 2026-01-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='management/'),
        ),
    ]
