# Generated by Django 6.0.1 on 2026-01-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_management_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='management',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.managementposition'),
        ),
    ]
