# Generated by Django 6.0.1 on 2026-01-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_coach_date_of_birth_coach_joined_date_coach_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menplayer',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.coach'),
        ),
        migrations.AddField(
            model_name='womenplayer',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.coach'),
        ),
    ]
