# Generated by Django 6.0.1 on 2026-01-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_menplayer_coach_womenplayer_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menplayer',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='womenplayer',
            name='coach',
        ),
    ]
