# Generated by Django 6.0.1 on 2026-01-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_menplayer_coach_remove_womenplayer_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menplayer',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='womenplayer',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
