# Generated by Django 6.0.1 on 2026-01-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_menplayer_number_alter_womenplayer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='team_type',
            field=models.CharField(choices=[('men', "Men's Team"), ('women', "Women's Team")], default='men', max_length=10),
        ),
    ]
