# Generated by Django 6.0.1 on 2026-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_coach_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team_type',
            field=models.CharField(blank=True, choices=[('men', "Men's Team"), ('women', "Women's Team")], max_length=10, null=True),
        ),
    ]
