# Generated by Django 6.0.1 on 2026-02-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_alter_season_league'),
        ('teams', '0011_alter_coach_team_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='position',
        ),
        migrations.RemoveField(
            model_name='menplayer',
            name='position',
        ),
        migrations.RemoveField(
            model_name='womenplayer',
            name='position',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='players/')),
                ('biography', models.TextField(blank=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.playerposition')),
                ('team_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.teamtype')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='CoachPosition',
        ),
        migrations.DeleteModel(
            name='Management',
        ),
        migrations.DeleteModel(
            name='ManagementPosition',
        ),
        migrations.DeleteModel(
            name='MenPlayer',
        ),
        migrations.DeleteModel(
            name='WomenPlayer',
        ),
    ]
