# Generated by Django 6.0.1 on 2026-02-05 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_alter_season_league'),
        ('teams', '0012_remove_management_position_remove_menplayer_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ManagementPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='coaches/')),
                ('biography', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('team_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.teamtype')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.coachposition')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='management/')),
                ('biography', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.managementposition')),
            ],
        ),
    ]
