# Generated by Django 6.0.1 on 2026-02-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_coachposition_managementposition_coach_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.playerposition'),
        ),
    ]
