# Generated by Django 6.0.1 on 2026-02-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.coachposition'),
        ),
        migrations.AlterField(
            model_name='management',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.managementposition'),
        ),
    ]
