# Generated by Django 6.0.1 on 2026-01-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Standing',
        ),
    ]
